local ADDON_NAME, CE = ...

CE.Data = CE.Data or {}

-- Planner fields are intentionally conservative heuristics, not guarantees.
-- estimatedAttemptMinutes = a useful amount of time to spend at the stop before moving on.
-- successWeight = relative chance of making collection progress during a typical stop (0-1).
-- chanceLabel = player-facing qualitative description. Exact drop rates are only shown when
-- we have a stable, well-established value.
CE.Data.regions = {
    timeless = {
        key = "timeless",
        name = "Timeless Isle",
        mapID = 554,
        fallbackStart = { x = 0.30, y = 0.75 },
        travelMinutesPerMapUnit = 7.0,
        objectives = {
            {
                key = "mount_561",
                kind = "mount",
                id = 561,
                name = "Thundering Onyx Cloud Serpent",
                x = 0.67,
                y = 0.59,
                source = "Huolon",
                method = "Rare drop",
                note = "Huolon patrols the Firewalkers' Path / Blazing Way area.",
                estimatedAttemptMinutes = 6,
                successWeight = 0.009,
                chanceLabel = "Very low per kill (~0.9% reported)",
                availabilityLabel = "Rare spawn",
                collectionWeight = 2.8,
            },
            {
                key = "pet_1323",
                kind = "pet",
                id = 1323,
                name = "Ashleaf Spriteling",
                x = 0.673,
                y = 0.441,
                source = "Leafmender",
                method = "Rare drop",
                estimatedAttemptMinutes = 6,
                successWeight = 0.18,
                chanceLabel = "Low to moderate per useful stop",
                availabilityLabel = "Rare spawn",
            },
            {
                key = "pet_1328",
                kind = "pet",
                id = 1328,
                name = "Ruby Droplet",
                x = 0.645,
                y = 0.271,
                source = "Garnia",
                method = "Rare drop",
                note = "Garnia is at Ruby Lake high on the island.",
                estimatedAttemptMinutes = 7,
                successWeight = 0.18,
                chanceLabel = "Low to moderate per useful stop",
                availabilityLabel = "Rare spawn",
            },
            {
                key = "pet_1329",
                kind = "pet",
                id = 1329,
                name = "Dandelion Frolicker",
                x = 0.456,
                y = 0.729,
                source = "Spritewood event",
                method = "Farm / event drop",
                note = "Interact with Neverending Spritewood, then kill the hostile sprites.",
                estimatedAttemptMinutes = 8,
                successWeight = 0.55,
                chanceLabel = "Good farmable opportunity",
                availabilityLabel = "Repeatable farm/event",
            },
            {
                key = "pet_1330",
                kind = "pet",
                id = 1330,
                name = "Death Adder Hatchling",
                x = 0.340,
                y = 0.740,
                source = "Imperial Python",
                method = "Rare drop",
                note = "Farm Death Adders in the Celestial Court woods while watching for Imperial Python.",
                estimatedAttemptMinutes = 7,
                successWeight = 0.22,
                chanceLabel = "Low to moderate per useful stop",
                availabilityLabel = "Rare replacement spawn",
            },
            {
                key = "pet_1333",
                kind = "pet",
                id = 1333,
                name = "Jademist Dancer",
                x = 0.255,
                y = 0.292,
                source = "Jademist Dancers",
                method = "Farmable drop",
                estimatedAttemptMinutes = 8,
                successWeight = 0.60,
                chanceLabel = "Good farmable opportunity",
                availabilityLabel = "Farmable mobs",
            },
            {
                key = "pet_1335",
                kind = "pet",
                id = 1335,
                name = "Ominous Flame",
                x = 0.460,
                y = 0.360,
                source = "Foreboding Flame",
                method = "Farmable drop",
                note = "Inside the Cavern of Lost Spirits.",
                estimatedAttemptMinutes = 8,
                successWeight = 0.55,
                chanceLabel = "Good farmable opportunity",
                availabilityLabel = "Farmable mobs",
            },
            {
                key = "pet_1336",
                kind = "pet",
                id = 1336,
                name = "Skunky Alemental",
                x = 0.3737,
                y = 0.7729,
                source = "Zhu-Gon the Sour",
                method = "Rare/event drop",
                estimatedAttemptMinutes = 7,
                successWeight = 0.22,
                chanceLabel = "Low to moderate per useful stop",
                availabilityLabel = "Rare/event spawn",
            },
            {
                key = "pet_1337",
                kind = "pet",
                id = 1337,
                name = "Spineclaw Crab",
                x = 0.310,
                y = 0.310,
                source = "Monstrous Spineclaw",
                method = "Rare drop",
                note = "Monstrous Spineclaw can appear along the Timeless Shore.",
                estimatedAttemptMinutes = 8,
                successWeight = 0.20,
                chanceLabel = "Low to moderate per useful stop",
                availabilityLabel = "Rare spawn",
            },
            {
                key = "pet_1338",
                kind = "pet",
                id = 1338,
                name = "Gulp Froglet",
                x = 0.640,
                y = 0.706,
                source = "Bufo",
                method = "Rare drop",
                estimatedAttemptMinutes = 7,
                successWeight = 0.20,
                chanceLabel = "Low to moderate per useful stop",
                availabilityLabel = "Rare spawn",
            },
            {
                key = "pet_1345",
                kind = "pet",
                id = 1345,
                name = "Swarmling of Gu'chi",
                x = 0.370,
                y = 0.700,
                source = "Gu'chi the Swarmbringer",
                method = "Rare drop",
                estimatedAttemptMinutes = 7,
                successWeight = 0.20,
                chanceLabel = "Low to moderate per useful stop",
                availabilityLabel = "Rare spawn",
            },
            {
                key = "pet_1348",
                kind = "pet",
                id = 1348,
                name = "Jadefire Spirit",
                x = 0.460,
                y = 0.360,
                source = "Spirit of Jadefire",
                method = "Rare drop",
                note = "Inside the Cavern of Lost Spirits. Pair this stop with Ominous Flame farming.",
                estimatedAttemptMinutes = 7,
                successWeight = 0.24,
                chanceLabel = "Low to moderate per useful stop",
                availabilityLabel = "Rare spawn",
            },
        },
    },
}
